name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    uses: ./.github/workflows/elixir-common.yml
    with:
      test_flags: "--exclude visual_test:true --exclude performance:true"
  visual:
    uses: ./.github/workflows/elixir-common.yml
    with:
      test_flags: "--only visual_test"
  performance:
    uses: ./.github/workflows/elixir-common.yml
    with:
      test_flags: "--only performance"
